apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-rebalancer-deployment
  labels:
    app: portfolio-rebalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-rebalancer
  template:
    metadata:
      labels:
        app: portfolio-rebalancer
    spec:
      containers:
        - image: httpd
          imagePullPolicy: Always
          name: portfolio-rebalancer
          ports:
            - containerPort: 80
              protocol: TCP
