apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pr
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - portfolio-rebalancer.localhost
      secretName: portfolio-rebalancer-secret
  rules:
    - host: portfolio-rebalancer.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pr
                port:
                  number: 80
