apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pr
spec:
  ingressClassName: nginx
  defaultBackend:
  service:
    name: pr
    port:
      number: 80
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pr
                port:
                  number: 80
