apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-rebalancer-certificate
spec:
  dnsNames:
    - portfolio-rebalancer.localhost
  secretName: portfolio-rebalancer-tls
  issuerRef:
    name: self-signed-issuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-rebalancer-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: portfolio-rebalancer-service
      port:
        number: 80
  tls:
    - hosts:
        - portfolio-rebalancer.localhost
      secretName: portfolio-rebalancer-tls
  rules:
    - host: portfolio-rebalancer.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-rebalancer-service
                port:
                  number: 80
