apiVersion: v1
kind: Service
metadata:
  name: portfolio-rebalancer-service
spec:
  type: ClusterIP
  selector:
    app: portfolio-rebalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
