apiVersion: v1
kind: Service
metadata:
  name: pr
  namespace: portfolio-rebalancer
spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: pr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
