name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Dependencies
        run: npm install

      - name: Check Formatting
        run: npm run format-check

      - name: Typecheck the Typescript
        run: npm run type-check

      - name: Run Tests
        run: CI=true npm run test
